from django.db import models

class Paper(models.Model):
  # the ID is auto-generated by the database
  title    = models.CharField(max_length=200)
  abstract = models.TextField()
  authors  = models.TextField()
  # fields below are NOT required
  logoUrl  = models.TextField() # this probably should be changed for a different field
  docUrl   = models.TextField()

  def __str__(self):
    return self.title